# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.document-core
canonical: https://interop.esante.gouv.fr/ig/fhir/document-core # the last part of canonical and id must be the same
name: FHIRFRDocumentCore # Should be an acronym
title: FR Document Core (FHIR)
description: Volet FHIR du guide d'implémentation Document Core.
publisher:
  name: Agence du Numérique en Santé (ANS) - 2-10 Rue d'Oradour-sur-Glane, 75015 Paris
  url: https://esante.gouv.fr
status: draft
version: 0.1.0 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
license: CC0-1.0
releaseLabel: ci-build # le release label doit être conforme au cycle de vie de la doctrine du ci-sis. Cf. https://interop.esante.gouv.fr/ig/documentation/mod_bonnes_pratiques.html#release-dun-ig-fhir dans la colonne "label de publication"

jurisdiction: urn:iso:std:iso:3166#FR "France (la)"

parameters: #Parameters list - https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
    shownav: 'true'
    path-expansion-params: '../../expansion-params.json' # for using French SNOMED CT Extension
    pin-canonicals: pin-all
    apply-contact: true
    logging:
      - tx #tx: Messages describing the use of the terminology server (for debugging)
      - html #html: Log when validating an html page (troubleshooting only - leave off)
      - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
      - init #init: Messages describing the start up process (for debugging)
      - progress #progress: Overall progress messages
    i18n-default-lang: fr # Default language
    apply-jurisdiction: true
    i18n-lang:
      - en
    translation-sources:
      - input/translations/en

dependencies:
  hl7.fhir.fr.core: 2.1.0
  hl7.fhir.uv.xver-r5.r4: 0.1.0
  ans.fhir.fr.annuaire: 1.1.0
  hl7.fhir.uv.fhir-clinical-document: latest
  ihe.pharm.mpd: 1.0.0-comment-2
  ans.fr.terminologies: latest
  hl7.fhir.eu.extensions: 1.3.0

pages:
    index.md:
        title: Accueil
    ressourcesFHIR-struc-gen.md:
        title: Structure générale document
    ressourcesFHIR-entete.md:
        title: Entête document
    ressourcesFHIR-corps.md:
        title: Corps d'un document
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
    translationinfo.md:
        title: Informations sur la traduction

menu:
    Accueil: index.html
    Structure générale document: ressourcesFHIR-struc-gen.html
    Entête document: ressourcesFHIR-entete.html
    Corps d'un document: ressourcesFHIR-corps.html
    Ressources de conformité: artifacts.html
    Autres ressources:
        "IG CDA": new-tab https://interop.esante.gouv.fr/ig/cda/document-core/index.html
        "IG Modèle métier": new-tab https://interop.esante.gouv.fr/ig/document-core/index.html
        "Espace de publication du CI-SIS": new-tab https://esante.gouv.fr/offres-services/ci-sis/espace-publication
        "Serveur Multi-terminologies": new-tab https://smt.esante.gouv.fr/
        "Serveur Multi-terminologies / FHIR": new-tab https://smt.esante.gouv.fr/fhir
        "IG terminologies et jeux de valeurs du CI-SIS": new-tab https://ansforge.github.io/IG-terminologie-de-sante/ig/main/index.html
        "Espace de tests du CI-SIS": new-tab https://interop.esante.gouv.fr/
        Sécurité: securite.html
        "Standard FHIR": new-tab https://hl7.org/fhir/R4/index.html
        "Documentation des guides d'implémentation de l'ANS": new-tab https://interop.esante.gouv.fr/ig/documentation/index.html
        Téléchargements et usage: downloads.html

groups:
  ressources-fhir-entete:
    name: Profils FHIR entête
    resources:
      - StructureDefinition/fr-bundle-document
      - StructureDefinition/fr-composition-document
      - StructureDefinition/fr-patient-document
      - StructureDefinition/fr-patient-ins-document
      - StructureDefinition/fr-practitionerRole-document
      - StructureDefinition/fr-practitioner-document
      - StructureDefinition/fr-organization-document
      - StructureDefinition/fr-device-auteur-document
      - StructureDefinition/fr-encounter-care-document
      - StructureDefinition/fr-location-document
      - StructureDefinition/fr-related-person-document

  ressources-fhir-corps:
    name: Profils FHIR corps
    resources:
      - StructureDefinition/fr-advance-directive-document
      - StructureDefinition/fr-adverse-event-document
      - StructureDefinition/fr-allergy-intolerance-document
      - StructureDefinition/fr-care-plan-document
      - StructureDefinition/fr-condition-document
      - StructureDefinition/fr-device-request-document
      - StructureDefinition/fr-device-use-statement-document
      - StructureDefinition/fr-diagnostic-report-document
      - StructureDefinition/fr-diagnostic-report-bio-chapter-document
      - StructureDefinition/fr-diagnostic-report-imaging-document
      - StructureDefinition/fr-document-reference-document
      - StructureDefinition/fr-encounter-document
      - StructureDefinition/fr-endpoint-wado-document
      - StructureDefinition/fr-family-member-history-document
      - StructureDefinition/fr-imaging-study-document
      - StructureDefinition/fr-immunization-document
      - StructureDefinition/fr-immunization-recommendation-document
      - StructureDefinition/fr-media-document
      - StructureDefinition/fr-medication-document
      - StructureDefinition/fr-medication-administration-document
      - StructureDefinition/fr-medication-statement-document
      - StructureDefinition/fr-service-request-document
      - StructureDefinition/fr-medication-dispense-document
      - StructureDefinition/fr-medication-request-document
      - StructureDefinition/fr-observation-contra-indications-document
      - StructureDefinition/fr-observation-laboratory-report-results-document
      - StructureDefinition/fr-observation-microorganism-detection-document
      - StructureDefinition/fr-observation-pregnancy-history-document
      - StructureDefinition/fr-observation-pain-score-document
      - StructureDefinition/fr-observation-pregnancy-document
      - StructureDefinition/fr-observation-radiation-exposure-document
      - StructureDefinition/fr-observation-work-related-accident-document
      - StructureDefinition/fr-observation-ald-document
      - StructureDefinition/fr-observation-prevention-document
      - StructureDefinition/fr-observation-assessment-document
      - StructureDefinition/fr-observation-social-history-document
      - StructureDefinition/fr-procedure-imaging-document
      - StructureDefinition/fr-procedure-document
      - StructureDefinition/fr-specimen-document
      - StructureDefinition/fr-observation-result-document
      - StructureDefinition/fr-task-patient-transport-document
      - StructureDefinition/fr-observation-vital-signs-panel-document
      - StructureDefinition/fr-observation-vital-signs-document
      - StructureDefinition/fr-body-structure-document
      - StructureDefinition/fr-observation-multiresistant-microorganism-document
      - StructureDefinition/fr-service-request-imaging-document

  data-type-fhir:
    name: Data Type Profiles
    resources:
      - StructureDefinition/fr-human-name-document
      - StructureDefinition/fr-accession-number-identifier-document
      - StructureDefinition/fr-study-instance-uid-identifier-document
